version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - wastedassign
    - whitespace
  disable:
    - containedctx
    - cyclop
    - depguard
    - dupl
    - err113
    - errorlint
    - exhaustive
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godot
    - godox
    - lll
    - maintidx
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - staticcheck
    - tagliatelle
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    revive:
      severity: error
      rules:
        - name: exported
          severity: warning
          disabled: false
        - name: indent-error-flow
          severity: warning
          disabled: false
        - name: var-naming
          arguments:
            - []
            - - ACL
              - API
              - ASCII
              - CPU
              - CSS
              - DNS
              - EOF
              - GUID
              - HTML
              - HTTP
              - HTTPS
              - ID
              - IP
              - JSON
              - LHS
              - QPS
              - RAM
              - RHS
              - RPC
              - SLA
              - SMTP
              - SQL
              - SSH
              - TCP
              - TLS
              - TTL
              - UDP
              - UI
              - UID
              - UUID
              - URI
              - URL
              - UTF8
              - VM
              - XML
              - XMPP
              - XSRF
              - XSS
              - VDC
              - DFW
              - VLAN
              - IAM
              - VCDA
              - NAT
              - VPN
              - BMS
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/orange-cloudavenue/cloudavenue-cli)
        - blank
        - dot
      custom-order: true
    gofumpt:
      module-path: github.com/orange-cloudavenue/cloudavenue-cli
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/orange-cloudavenue/cloudavenue-cli
  exclusions:
    generated: lax
