site_name: CAV (Cloud Avenue CLI)
theme:
  name: material
  features:
    - navigation.instant
    - navigation.footer
    - navigation.tabs
  palette: 
    scheme: slate
    primary: deep orange
    accent: indigo
  icon:
    logo: fontawesome/solid/terminal

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Command:
    - command/cav.md
    - get: 
      - command/cav_get.md
      - VDC: command/cav_get_vdc.md
      - S3: command/cav_get_s3.md
      - T0: command/cav_get_t0.md
      - Public IP: command/cav_get_publicip.md
      - EdgeGateway: command/cav_get_edgegateway.md
    - create: 
      - command/cav_create.md
      - VDC: command/cav_create_vdc.md
      - S3: command/cav_create_s3.md
      - Public IP: command/cav_create_publicip.md
      - EdgeGateway: command/cav_create_edgegateway.md
    - delete:
      - command/cav_delete.md
      - VDC: command/cav_delete_vdc.md
      - S3: command/cav_delete_s3.md
      - Public IP: command/cav_delete_publicip.md
      - EdgeGateway: command/cav_delete_edgegateway.md
    - completion:
      - command/cav_completion.md
      - bash: command/cav_completion_bash.md
      - zsh: command/cav_completion_zsh.md
      - fish: command/cav_completion_fish.md
      - powershell: command/cav_completion_powershell.md
    - version: command/cav_version.md

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/orange-cloudavenue/cloudavenue-cli

repo_url: https://github.com/orange-cloudavenue/cloudavenue-cli
repo_name: orange-cloudavenue/cloudavenue-cli

copyright: Copyright &copy; 2023 - 2024 Orange - Cloud Avenue

