# Check if the code generation is up to date.
name: gen-doc

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
    paths:
      - '**.go'
  
jobs:
  generate:
    name: gen-doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v3.5.0
      - uses: actions/setup-go@v5.0.2 # v4.0.0
        with:
          go-version-file: 'go.mod'
      - run: make doc
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'make doc' command and commit."; exit 1)